site_name: RCL
site_url: https://docs.ruuda.nl/rcl
repo_url: https://github.com/ruuda/rcl
strict: true

theme:
  name: null
  custom_dir: docs/theme

markdown_extensions:
  - codehilite
  - footnotes
  - toc:
      permalink: true
      permalink_title: null

nav:
  - "Overview": "index.md"
  - "User guide":
      - "Tutorial": "tutorial.md"
      - "Installation": "installation.md"
      - "Syntax highlighting": "syntax_highlighting.md"
      - "Using Ninja": "using_ninja.md"
      - "Changelog": "changelog.md"
  - "Language guide":
      - "Syntax": "syntax.md"
      - "Strings": "strings.md"
      - "Null": "null.md"
      - "Imports": "imports.md"
      - "Functions": "functions.md"
      - "Types": "types.md"
      - "Glossary": "glossary.md"
  - "Language reference":
      - "Standard library": "stdlib.md"
      - "Dict": "type_dict.md"
      - "List": "type_list.md"
      - "Set": "type_set.md"
      - "String": "type_string.md"
      - "Python bindings": "python_bindings.md"
  - "Command reference":
      - "rcl": "rcl.md"
      - "rcl evaluate": "rcl_evaluate.md"
      - "rcl format": "rcl_format.md"
      - "rcl highlight": "rcl_highlight.md"
      - "rcl query": "rcl_query.md"
  - "Development":
      - "Testing": "testing.md"
      - "Tree-sitter": "tree_sitter.md"
