[toolchain]
channel = "1.70.0"
components = ["rustfmt", "clippy"]
targets = [
  # Default regular build.
  "x86_64-unknown-linux-gnu",
  # For building a static binary.
  "x86_64-unknown-linux-musl",
  # For WASM.
  "wasm32-unknown-unknown",
]
