# This file is generated, see build.rcl in the repository root.

authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "Support for the RCL configuration language."
id = "rcl"
name = "RCL"
repository = "https://github.com/rcl-lang/zed-rcl"
schema_version = 1
version = "0.8.0"

[grammars]
rcl = { commit = "e371920de7d1921a4ac9c6d78bd74ea3e94dfade", repository = "https://github.com/rcl-lang/tree-sitter-rcl" }
