# This file is generated, see build.rcl in the repository root.

authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "Support for the RCL configuration language."
id = "rcl"
name = "RCL"
repository = "https://github.com/rcl-lang/zed-rcl"
schema_version = 1
version = "0.11.0"

[grammars]
rcl = { commit = "a6e42ed21e23c32b76c1d8cb13ec60cdd0ed860d", repository = "https://github.com/rcl-lang/tree-sitter-rcl" }
