# This file is generated, see build.rcl in the repository root.

[dependencies]
rcl = { path = ".." }
wasm-bindgen = { default-features = false, features = ["std"], version = "=0.2.89" }

[lib]
crate-type = ["cdylib"]

[package]
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "WASM entry points for RCL functionality."
edition = "2021"
license = "Apache-2.0"
name = "rcl-wasm"
version = "0.12.0"

[target]
"cfg(wasm)" = { dev-dependencies = { allocator-api2 = "=0.2.15", compiler_builtins = "=0.1.103", dlmalloc = "=0.2.4", fortanix-sgx-abi = "=0.5.0", getopts = "=0.2.21", hashbrown = "=0.14.2", hermit-abi = "= 0.3.2", libc = "=0.2.150", r-efi = "=4.2.0", r-efi-alloc = "=1.0.0", rustc-demangle = "=0.1.23", unicode-width = "=0.1.10", wasi = "=0.11.0" } }
